# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('anonymous_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('anonymous_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_type', models.IntegerField(choices=[(0, b'Member dance only'), (1, b'Member lesson and dance'), (2, b'Non-member dance only'), (3, b'Non-member lesson and dance'), (4, b'Tips for blues'), (5, b'UC Santa Cruz student'), (6, b'Exempt'), (7, b'DJ / Instructor'), (8, b'Volunteer'), (9, b'Comp')])),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_type', models.IntegerField(blank=True, choices=[(0, b'Cash'), (1, b'Credit')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.IntegerField(choices=[(0, b'Member dance only'), (1, b'Member lesson and dance'), (2, b'Non-member dance only'), (3, b'Non-member lesson and dance'), (4, b'Tips for blues'), (5, b'UC Santa Cruz student'), (6, b'Exempt'), (7, b'DJ / Instructor'), (8, b'Volunteer'), (9, b'Comp')])),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rate_lst', to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Venue'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lst', to='event.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('date', 'venue')]),
        ),
    ]
